modLoader="javafml"
loaderVersion="[47,]"
license="MIT"

[[mods]]
modId="zomboidcraft"
version="1.0"
displayName="ZomboidCraft"
credits="Example"
authors="ChatGPT"
description='''
A simple zombie infection and bleeding mod.
'''

[[dependencies.zomboidcraft]]
modId="forge"
mandatory=true
versionRange="[47,]"
ordering="NONE"
side="BOTH"

[[dependencies.zomboidcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
